development:
  facebook:
    app_id: 1523017461317534
    secret: 7596444ccf4fabc1b5c935e8c472e5ae

  twitter:
    app_id: JNEmHHeu85BKjxmAUX7NbQ
    secret: i6oRtEKQ6OpZnyxZC4wv06mtfMIgPLRHCMTWOecCs

test:
  facebook:
    app_id: 1523017461317534
    secret: 7596444ccf4fabc1b5c935e8c472e5ae
  twitter:
    app_id: 12345
    secret: abcdef

staging:
  facebook:
    app_id: 1523017461317534
    secret: 7596444ccf4fabc1b5c935e8c472e5ae

  twitter:
    app_id: JNEmHHeu85BKjxmAUX7NbQ
    secret: i6oRtEKQ6OpZnyxZC4wv06mtfMIgPLRHCMTWOecCs

production:
  facebook:
    app_id: 1523017461317534
    secret: 7596444ccf4fabc1b5c935e8c472e5ae

  twitter:
    app_id: JNEmHHeu85BKjxmAUX7NbQ
    secret: i6oRtEKQ6OpZnyxZC4wv06mtfMIgPLRHCMTWOecCs